# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - 'main'
      - 'java'
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker base Image
        id: meta_base
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: vijayjangir/pre-commit
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Extract metadata (tags, labels) for Docker jdk 17 Image
        id: meta_jdk17
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: vijayjangir/pre-commit
          tags: |
            type=semver,pattern={{version}},suffix=java17
            type=semver,pattern={{major}}.{{minor}},suffix=java17
    
      - name: Extract metadata (tags, labels) for Docker jdk21 Image
        id: meta_jdk21
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: vijayjangir/pre-commit
          tags: |
            type=semver,pattern={{version}},suffix=java21
            type=semver,pattern={{major}}.{{minor}},suffix=java21
        
                
      - name: Build and push Docker image base
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_base.outputs.tags }}
          labels: ${{ steps.meta_base.outputs.labels }}

      - name: Build and push Docker image jdk17
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            PACKAGES_LIST=git bash openjdk17 maven
          push: true
          tags: ${{ steps.meta_jdk17.outputs.tags }}
          labels: ${{ steps.meta_jdk17.outputs.labels }}
  
      - name: Build and push Docker image jdk21
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            PACKAGES_LIST=git bash openjdk21 maven
          push: true
          tags: ${{ steps.meta_jdk21.outputs.tags }}
          labels: ${{ steps.meta_jdk21.outputs.labels }}
  
  
      
      - name: "Docker Hub Description"
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_README }}
          repository: vijayjangir/pre-commit
